### ISSUE TITLE
Older posts does not show on SelfSteem and only one post shows

### ISSUE THREAD

**Issue by ehfd** [jnordberg/selfsteem#14]
![image](https://user-images.githubusercontent.com/8457324/51036255-e54e6d00-15ef-11e9-9fe4-04047145f50f.png)  
https://jnordberg.github.io/selfsteem/  
On the main demo page, as well as other custom pages, the Older posts button does not show, and only one post shows on the webpage.  
A prompt fix may be needed to keep the program to its purpose.

**Comment by mvalente** [comment]
Ditto
