### ISSUE TITLE
Selfsteem stucks on loading?

### ISSUE THREAD

**Issue by ehfd** [jnordberg/selfsteem#3]
Selfsteem looks stuck when loading it, even when accessing your demo. 
Is this a problem with the node API or something else?
Please look into this. Thank you.

**Comment by jnordberg** [comment]
Yeah, need to switch it to https://api.steemit.com

**Comment by jnordberg** [comment]
Should be enough to bump the dsteem version to latest and change the node config here

https://github.com/jnordberg/selfsteem/blob/master/config.json#L8

I would appreciate a PR for that! :)

**Comment by ehfd** [comment]
Done. Do other version dependencies need to be updated also?

**Comment by jnordberg** [comment]
Don't think so, does it work with your patches?

**Comment by ehfd** [comment]
> secp256k1@3.4.0 install /media/user/hdd/skim/etc/selfsteem-master/node_modules/dsteem/node_modules/secp256k1
> npm run rebuild || echo "Secp256k1 bindings compilation fail. Pure JS implementation will be used."


> secp256k1@3.4.0 rebuild /media/user/hdd/skim/etc/selfsteem-master/node_modules/dsteem/node_modules/secp256k1
> node-gyp rebuild

I see this, but the website itself looks okay.

**Comment by ehfd** [comment]
This shouldn't give a problem later maybe?

**Comment by jnordberg** [comment]
Yeah that's not a problem

**Comment by ehfd** [comment]
OK thanks that's about it
Thanks for developing this :)
I am using this handy so that I could sync this automatically with my steemit posts.
